#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t cheminf2019olcc\
                         -C "start_jupyter -t -T @tool cheminfOLCC2019.ipynb" \
                         -u anaconda-7\
                         -r none\
                         -w headless

